  # Server
server:
  port: 8084

  # Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
    registerWithEureka: true
    fetchRegistry: true
  
  # Spring
spring:
  application:
    name: auth-service

  # H2 Database
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:cred
    driverClassName: org.h2.Driver
    username: sa
    password: password

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect