server:
  port: 8085

spring:
  application:
    name: API_GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**,/signUp,/auth/login

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**,/staffs/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**

        - id: EMAIL_SERVICE
          uri: http://localhost:9092/email/forgot/{email}
          predicates:
            - Path=/email/**






eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8762/eureka

#logging:
#  level:
#    org.springframework: DEBUG











