server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: user-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8762/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
      web:
        exposure:
          include: health

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instance:
      ratingHotelFallback:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED







